### ISSUE TITLE
False positive anti-spam triggers.

### ISSUE THREAD

**Issue by unnamed25** [FPtje/Falcos-Prop-protection#328] opened 2024-03-05 16:17 UTC
Hello, I have some problem with this addon.
When anti-spam is enabled, it triggers a false positive on the spawn of some entities, as well as the use of some tools.
Currently having problems with:
sent_deployableballoons entity from Wiremod - Becomes a ghost after spawn, which is why have to constantly pickup him through physgun.
wire_expression2 tool from Wiremod - E2 chip becomes a ghost after spawn.
Question, is this an FPP bug or do I have some problems with the server?
I didn’t touch any settings related to anti-spam, so they are all standard.

**Comment by FPtje** [comment] 2024-03-06 21:14
This could happen when some anti prop kill goes its own way. FPP did have bugs with wiremod, but those were fixed in like 2010. 

There was a recent change that broke something before fixing it again. Maybe updating FPP once again will work.

It's always a good idea to look for errors in the server console. Those will give a good indication of what's wrong.

I'll close the issue assuming it is indeed on your side, but feel free to post blow this comment if you have more info or questions. I'll get a notification even after the issue is closed.

**Comment by FPtje** [comment] 2024-03-09 16:49
Looks like you're right! Confirmed and fixed!

FPP exists since 2008, how is this still a bug?

**Closed by FPtje** 2024-03-09 16:49 UTC
