### ISSUE TITLE
Whitelist

### ISSUE THREAD

**Issue by BearRP** [FPtje/Falcos-Prop-protection#283] opened 2020-12-22 07:58 UTC
I made a ticket a few days ago about default props coming back, I have props already on the blacklist but the default props keep getting readded. Im trying to make it a whitelist and having the buildings and barrels on there makes that difficult

**Comment by FPtje** [comment] 2020-12-22 08:14
Could you check the server log for errors? Sounds like an error would precede this

**Comment by BearRP** [comment] 2020-12-23 05:36
I dont have any errors in my console and tool blacklist works, is there any way to stop the  default prop feature

**Comment by BearRP** [comment] 2020-12-23 05:39
theres a prop that crashes my server when its spawned so i cant really spawn it to blacklist it

**Comment by FPtje** [comment] 2020-12-25 13:46
## Adding models without spawning
Regarding adding blocked models without spawning them, this can be done as follows:

- Right click a prop and select `Copy to clipboard`
![hl2_2020-12-25_14-24-40](https://user-images.githubusercontent.com/1202014/103136013-f7325900-46bc-11eb-8758-cf8b9faa52be.png)
- Open the console, and enter the following:
  ```
  FPP_AddBlockedModel "<paste from clipboard using Ctrl+V>"
  ```
  **Make sure** there are double quotes around the model as shown below:
  ![hl2_2020-12-25_14-26-10](https://user-images.githubusercontent.com/1202014/103136030-25b03400-46bd-11eb-83af-61e6b8ce86ba.png)
- Press enter
- You should see a message at the bottom of your screen saying the model was added.
  ![steam_2020-12-25_14-28-20](https://user-images.githubusercontent.com/1202014/103136067-76279180-46bd-11eb-86d2-aa4d995376bc.png)


## Whitelist
Regarding the blocked models, I really cannot reproduce it. Here's what I tried:
- Turn on blocked models whitelist option:
 ![hl2_2020-12-25_14-32-13](https://user-images.githubusercontent.com/1202014/103136261-17631780-46bf-11eb-8cfa-6f37837a0b95.png)
- Remove all models from the `Show blocked models` list, and added `models/props_junk/wood_crate001a.mdl`
- Restart server
- Look at the `Show blocked models` again:
  ![hl2_2020-12-25_14-31-56](https://user-images.githubusercontent.com/1202014/103136298-79238180-46bf-11eb-80cb-817aef047ad2.png)
- Verify that this box is really the only prop I can spawn. 


I've verified that this works on both the native SQLite database and on MySQL. This is what the blocked models look like in MySQL:
![MySQLWorkbench_2020-12-25_14-39-31](https://user-images.githubusercontent.com/1202014/103136289-6f018300-46bf-11eb-8118-c305b51f5e6f.png)

There must be something on your end that prevents this from working properly. Try this in a server with no addons installed except for FPP. When that works, try adding addons one by one until it breaks. The addon that breaks it is should then be removed and reported to the author.

**Comment by FPtje** [comment] 2020-12-25 13:46
Closing the issue again. Discussion can continue in this issue, please do not open new issues, I will see new posts in this issue.

**Closed by FPtje** 2020-12-25 13:46 UTC
